### ISSUE TITLE
Allow more room to write an accessibility description

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#101]
<img src="https://user-images.githubusercontent.com/813383/91670591-eca0f200-eb16-11ea-8dc0-9be3a8beb4ca.jpg" alt="Screenshot of Sunlit accessibility description dialog" width="320">

While an accessibility description shouldn’t be too long, to be effective it probably requires more characters than that currently able to be displayed in this dialog. Editing this text is made more difficult given iOS’s current text selection methods (infuriating would be an understatement!).

If this dialog displayed two lines of text, the usability of this important feature would be 100% better.

**Comment by manton** [comment]
I believe this will require creating a custom dialog, since UIAlertController doesn't support multi-line text fields.

**Comment by paulrobertlloyd** [comment]
@manton I believe so. I did a bit research hoping a could change a value or add an attribute, but it’s not so easy, I’m afraid.

**Comment by cheesemaker** [comment]
This is now in the 3.2 branch
