### ISSUE TITLE
Add multiple photos in one hit

### ISSUE THREAD

**Issue by adamprocter** [microdotblog/sunlit#107]
Tap plus and then be able to select more than one image, May need a multi select mode on so as not to slow down one image posting mind

**Comment by cheesemaker** [comment]
The iOS 14 photo picker supports multiple image selection. We need to explicitly add support for this so this is a good ticket. Just a comment that it will only be supported on >= iOS 14.

**Comment by cheesemaker** [comment]
This is now in the 3.1 branch and will be made available in the next beta build.
