### ISSUE TITLE
Signed out of Micro.blog but mentions and bookmarks tab still shows

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#133]
Signed out of Micro.blog, but the mentions and bookmarks tabs are still visible (although tapping on the icons in the tab bar or swiping to these view doesn’t take you to the respective screens). Sunlit 3.2 (379)

**Comment by paulrobertlloyd** [comment]
Oooh boy… restarting the app and find myself signed back into Micro.blog 🤪

**Comment by cheesemaker** [comment]
So the actual bug here is related to Micro.blog and Sunlit sharing logins in 3.2. I just ran into this with another issue as well and it's making me re-think the shared login.

**Comment by paulrobertlloyd** [comment]
Just for completeness… the profile tab shows also (which I think it does when signed out), but tapping on that tab doesn’t work either. There’s actually no discernible way to sign back in.

**Comment by cheesemaker** [comment]
Possible solutions:
1. Don't share logins - this makes the first time use worse though
2. Don't allow logging out of Micro.blog from within Sunlit? Or maybe there's an edge case where you can let them logout but only if they don't have the Micro.blog app on their device?
3. Figure out how to totally clear the data, but the downside is that it would also log them out of the Micro.blog app which they might not have intended to do.

Not sure what the right approach here is. I really like how it improves the first-use experience for people that have already logged into Micro.blog

**Comment by cheesemaker** [comment]
@paulrobertlloyd if you completely delete Sunlit from your phone (not just the data) it should allow you to re-set everything up again. I just verified that locally.

**Comment by cheesemaker** [comment]
Ok, so this will be resolved in the next Beta. Basically, we have changed the logic to only import login information from Micro.blog once. After that, if you logout, you're on your own.

**Comment by cheesemaker** [comment]
When you can, please re-test this with the latest beta and let me know if we can close.

**Comment by cheesemaker** [comment]
This is fixed in 3.2 beta build 384
