### ISSUE TITLE
Share sheet not working

### ISSUE THREAD

**Issue by mcg** [microdotblog/sunlit#137]
Using Sunlit from TestFlight version 3.2(383). 

When I try to share a picture to Sunlit it fails with an error dialog that says,
> Sunlit setup has not been completed, Please launch Sunlit and login. 

I am logged in to Sunlit and I’ve tried re-logging in as well as reinstalling. Same error.

**Comment by cheesemaker** [comment]
Thank you. Found and fixed. This is fixed in the next beta (3.2 build 385)
