### ISSUE TITLE
Sign in keyboard is incorrect type

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#57]
Sign in screen says:

> Enter your Micro.blog email address or the URL of an external blog

However, the keyboard shown is that for an email, and therefore doesn’t allow you to type `://`. If entering a URL without `https://`, the next button doesn’t submit the form.

**Comment by manton** [comment]
Related to #56.

**Comment by cheesemaker** [comment]
Posting to Micropub accounts is still supported but initial sign-in requires a Micro.blog account. The instructions for this screen have been updated so the keyboard for this is now correct.
