### ISSUE TITLE
Settings page has ‘Sign out of Micro.blog’ link when not signed in

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#59]
I’ve not signed in, but at the bottom of the settings screen there is a link that says ‘Sign Out of Micro.blog’. Clicking it asks if you want to sign out. If select ‘Sign out’, text is still shown.

**Comment by cheesemaker** [comment]
You shouldn't be able to access the settings screen when not logged in. This is fixed in the next beta.
