### ISSUE TITLE
Adding URL to login screen doesn’t work

### ISSUE THREAD

**Issue by kimonostereo** [microdotblog/sunlit#61]
The startup/login screen says to enter email or external URL but only email works. Once I use email and verify account I can add my external blog.

**Comment by manton** [comment]
Thanks, this is a limitation in the first beta. We should have removed that "external blog" reference in the text until that was working. Sorry about the confusion!

**Comment by kimonostereo** [comment]
No problem!  Thanks for the new beta! It’s beautiful!
