### ISSUE TITLE
Can’t sign in using external URL

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#62]
1. Go to settings page (only place can sign in with external URL given #57)
2. Select ‘WordPress or Micropub weblog
3. Tap ‘Sign in’ next to External Weblog
4. Enter URL
5. Complete IndieAuth flow
6. Redirected back to Sunlit

‘Micro.blog hosted weblog’ is still selected. Cannot post to external website.

**Comment by manton** [comment]
Thanks @paulrobertlloyd. If you close the settings screen and open it again, does it show your external blog info?

**Comment by paulrobertlloyd** [comment]
@manton Nope. It resolutely stays stuck on ‘Micro.blog hosted weblog’ 😕

**Comment by smithtimmytim** [comment]
I had this issue this morning too.

**Comment by manton** [comment]
@paulrobertlloyd @smithtimmytim What kind of blog software are you using?

**Comment by manton** [comment]
Should be fixed in the next beta.
