### ISSUE TITLE
Posting to Movable Type doesn’t work

### ISSUE THREAD

**Issue by kimonostereo** [microdotblog/sunlit#63]
Tried a few test posts. Each one stated “Successfully posted!” But when I tap View Post, I get a 404. 

The URL generated ifor the post is https://ohmypizza.com/micro/2020/07/post-1.php

**Comment by manton** [comment]
Movable Type is not supported in this beta. I think all the code is in there to support it, so hopefully it can be enabled.

**Comment by manton** [comment]
I think this is fixed for the next beta. Going to close for now.

**Comment by manton** [comment]
Re-opening this issue since publishing is still not working for @kimonostereo. It creates a post in Movable Type but with no content.

**Comment by kimonostereo** [comment]
Tested the latest testflight beta and it has the same results as the previous beta:
- Credentials authenticate
- A post is created in Movable Type but there isn't any content in the post
- The post is published but doesn't actually generate an actual post that is reachable via a web browser. I get a 404 error on my site when going to the URL. Example: https://ohmypizza.com/micro/2020/08/post.php
- Previous Sunlit would create an actual post file name using the text that is typed in the Sunlit body. Example: https://ohmypizza.com/micro/2020/08/beams-tokyo-japan---december.php

**Comment by manton** [comment]
@kimonostereo Does the photo get uploaded under the assets in MT?

**Comment by manton** [comment]
I installed a new copy of Movable Type to test this. Fixed in the latest beta I'm uploading now. Thanks!
