### ISSUE TITLE
Can’t sign in using email address

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#65]
Sign in screen says:

> Enter your Micro.blog email address or the URL of an external blog

I enter the email address associated with my Micro.blog account, and get the message:

> unsupported URL

This feels especially frustrating given #57!

**Comment by manton** [comment]
This happened to be once before but I'm not sure how. Can you force quit the app and try again? Or if you set up any settings, try going into Settings and signing out too. (I think something is saved in a weird state.)

**Comment by paulrobertlloyd** [comment]
Ah yes, force quitting the app lets me sign in with Micro.blog.

**Comment by cheesemaker** [comment]
I figured this out. This occurs after you logout from settings. We were incorrectly blasting the Micro.blog endpoint so calls to login were erroring out with incorrect URLs. This will be fixed in the next beta build.
