### ISSUE TITLE
Don't show usernames when replying

### ISSUE THREAD

**Issue by manton** [microdotblog/sunlit#68]
When replying, don't auto-fill the text field to include the usernames you're replying to. Let the user have the full text field to type their reply, and then behind the scenes before sending the reply, prepend the `@username`.

For conversations, same behavior. It will be a little weird because it won't @-mention anyone except the original author, but I think it's the most expected behavior. At least for 3.0 without a more advanced reply UI.

**Comment by cheesemaker** [comment]
This is fixed in the next Beta build.
