### ISSUE TITLE
Posts with titles not shown in Sunlit

### ISSUE THREAD

**Issue by jsonbecker** [microdotblog/sunlit#76]
Sunlit will show [this post](https://micro.json.blog/2020/08/07/hampden-rubble.html), but not [this post](https://micro.json.blog/2020/08/07/gracies-face.html).

There are two main differences. In the post that doesn't show up, the multiple images are within a `div` rather than a "top level" `img` tag. The other cause could be the text before the images rather than after-- but I think that Sunlit can deal with that.

My expectation is that both posts would appear in Sunlit.

**Comment by manton** [comment]
We've been talking about how to solve this and have a couple ideas. The main problem is how Micro.blog treats posts with titles differently. In your example, it would be easy to support both posts, but the "real" solution is to figure out the best way to support longer photo posts in Sunlit. Then that will take care of this issue as well.

**Comment by manton** [comment]
I think this is now resolved (for new posts). We may make further improvements later.
