### ISSUE TITLE
Grey images - some posts

### ISSUE THREAD

**Issue by adamprocter** [microdotblog/sunlit#79]
Sometimes when I scroll some images appear grey and don’t seem to load. Tapping image doesn’t load them either however tapping Open in Safari the posts will load fine. 

I am not sure if there is any similarities with posts as it’s different users plus Force quitting sunlit seems to load some previous grey images and some more images appear in the total timeline but some different ones are grey normally near the bottom but again sometimes a photo will load after a few grey images so it’s not just the bottom of the list. 

Sometimes the timeline is longer and loads more
Posts and sometimes it stops earlier too. 

iPhone X 
iOS 13.6

**Comment by manton** [comment]
Thanks. Not sure if this is the same thing you're seeing, but I've noticed on some screens (like Discover) that the photos won't load until scrolling.

**Comment by manton** [comment]
@adamprocter Let us know if this is still happening in the latest beta. Should be much better.

**Comment by adamprocter** [comment]
Seems much improved with 337. Feel free to close

**Comment by manton** [comment]
Great, thanks.
