### ISSUE TITLE
Post with multiple photos not showing in profile

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#87]
This is my profile in Sunlit currently:

<img src="https://user-images.githubusercontent.com/813383/91096030-41df8e00-e655-11ea-916f-c9d5c81f0322.PNG" alt="Screenshot of profile page in Sunlit" width="320">

It doesn’t show this more recent post: https://paulrobertlloyd.com/photos/1597876298/ which appears in Micro.blog (with both photos visible). It doesn’t contain a title (#76), but it does contain 2 photos and some additional HTML. Here is the item in [my JSON feed](https://paulrobertlloyd.com/feed.json):

```json
{
    "id": "https://paulrobertlloyd.com/photos/1597876298/",
    "url": "https://paulrobertlloyd.com/photos/1597876298/",
    "title": "",
    "content_html": "<p>Shadows.</p><figure class=\"align-none\">\n  <div class=\"photos\" style=\"--columns: 2\"><img class=\"u-photo\" src=\"https://res.cloudinary.com/paulrobertlloyd/image/fetch/c_fill,f_auto,q_auto,w_960/https://paulrobertlloyd.com/images/photos/1597876298.jpg\" srcset=\"\" sizes=\"\" width=\"960\" alt=\"Harsh shadows on concrete beach shelters.\" loading=\"lazy\"><img class=\"u-photo\" src=\"https://res.cloudinary.com/paulrobertlloyd/image/fetch/c_fill,f_auto,q_auto,w_960/https://paulrobertlloyd.com/images/photos/1597876299.jpg\" srcset=\"\" sizes=\"\" width=\"960\" alt=\"Harsh shadows on concrete steps.\" loading=\"lazy\"></div>\n</figure>\n",
    "date_published": "2020-08-19T23:31:38.257+01:00"
}
```

**Comment by paulrobertlloyd** [comment]
Just to follow up with another example.

### Micro.blog for iOS

Included for the sake of comparison.

* Timeline. Latest post from me with three images shown:
  
  <img src="https://user-images.githubusercontent.com/813383/91316743-18d41000-e7b1-11ea-806d-b85448edfdd8.PNG" alt="" width="320">

* Profile. Latest post from me with three images shown:
  
  <img src="https://user-images.githubusercontent.com/813383/91316997-66507d00-e7b1-11ea-9466-d694b3bd33c7.PNG" alt="" width="320">

### Sunlit

* Timeline. Latest post from me with three images shown:
  
  <img src="https://user-images.githubusercontent.com/813383/91316463-be3ab400-e7b0-11ea-8899-d80490c68c5f.PNG" alt="" width="320">

* Profile. Latest post from me **is not** shown:
  
  <img src="https://user-images.githubusercontent.com/813383/91316602-e75b4480-e7b0-11ea-958e-4adf79eb3098.PNG" alt="" width="320">

If I look at your own timeline @manton, your recent post that included several screenshots is shown in your profile (although it should also be noted that it’s only possible to view the first photo from this view – separate bug?)

**Comment by cheesemaker** [comment]
I'm confused if this is still an issue. Is this at all related to this other issue?

https://github.com/microdotblog/sunlit/issues/105

**Comment by paulrobertlloyd** [comment]
I think there are two separate issues:

* Show all photos in a post (#105)
* Show a post that has multiple photos on a user’s profile (this issue)

That said, opening Sunlit just now, my profile page refreshed, and posts that have multiple photos are now showing. Maybe it was a caching issue?

**Comment by cheesemaker** [comment]
It's possible that it could have been fixed by this issue that was fixed last week:
https://github.com/microdotblog/sunlit/issues/76

I'll close this for now, but please re-open if you see it again.

**Comment by paulrobertlloyd** [comment]
Ah, that seems quite probable! Thanks @cheesemaker.
