### ISSUE TITLE
Massive gap above and below vertical video on blog from Sunlit

### ISSUE THREAD

**Issue by adamprocter** [microdotblog/sunlit#89]
Post vertical video from sunlit massive gap above and below video didn’t happen from MB iOS App

From sunlit
https://discursive.adamprocter.co.uk/2020/08/25/a-good-day.html

From MB iOS app
https://discursive.adamprocter.co.uk/2020/08/25/good-day.html

**Comment by adamprocter** [comment]
really large on small / mobile

**Comment by manton** [comment]
Thanks. Appears to be the wrong width/height attributes set on the video.

**Comment by manton** [comment]
Should be fixed now.
