### ISSUE TITLE
Can’t view conversations on photos shown in profile section

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#90]
In discover section:
* Tap on a photo
* Photo sheet pops up
* Tap on conversation icon
* Photo sheet pops down, slides over to conversation view for the photo

In profile section:
* Tap on a photo
* Photo sheet pops up
* Tap on conversation icon
* Photo sheet pops down, but no conversation view is shown.

**Comment by manton** [comment]
Fixed for the next beta.

**Comment by paulrobertlloyd** [comment]
@manton Wow, that was quick! 😁
