### ISSUE TITLE
sunlit.io not accessible on 4G

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#92]
Webpage over Wi-Fi:

<img src="https://user-images.githubusercontent.com/813383/91500528-997f3300-e8bb-11ea-8d2f-234730c76ee8.PNG" width="320">

On 4G (Three, UK):

<img src="https://user-images.githubusercontent.com/813383/91500541-a13ed780-e8bb-11ea-8f37-2858f0d94c66.PNG" width="320">

Hard to know if the domain is blacklisted somehow on my cellular network, or if it’s a certificate issue of some kind?

**Comment by manton** [comment]
This may be an IPv6 issue, which we've had in the past. That would explain the inconsistency on some networks. Should be fixable on the server side.

**Comment by manton** [comment]
I'm migrating sunlit.io to be a Micro.blog-hosted site, which will solve this. Thanks for reporting it.
