### ISSUE TITLE
Need to support push notifications

### ISSUE THREAD

**Issue by cheesemaker** [microdotblog/sunlit#94]

**Comment by manton** [comment]
The API for registering a device for push notifications is documented here: https://github.com/hartlco/Icro/issues/5#issuecomment-530878037

**Comment by cheesemaker** [comment]
Client side implementation is done. Need server certs.

**Comment by manton** [comment]
Cert is mostly ready to go. Will be deploying on Tuesday with the M.b 2.0 rollout.

**Comment by cheesemaker** [comment]
This is done. Woohoo!
