### ISSUE TITLE
Add a setting to allow full-size image uploads

### ISSUE THREAD

**Issue by cheesemaker** [microdotblog/sunlit#95]

**Comment by cheesemaker** [comment]
Labeling this a bug since without this, non Micro.blog hosts cannot post full size images.

**Comment by manton** [comment]
The app already resizes before uploading, so renaming this. I don't really consider this a bug, but having a setting would be good. It should only be shown when an external blog is configured, and we can default to off.

**Comment by cheesemaker** [comment]
I'm moving this out a release. It's not critical and would require a redesign to settings or the post screen.

**Comment by manton** [comment]
Thinking more about this, I'm not sure we should do this feature. It adds some settings complexity, potentially slows down uploads, and does not apply for most Sunlit users who are using Micro.blog-hosted blogs.

**Comment by cheesemaker** [comment]
I believe we may need this if we support non-Micro.blog implementations but otherwise it's not really needed. In that case, the earliest we would need this is 3.4.

**Comment by manton** [comment]
I'm going to close this. I don't see us supporting this in the near future.
