### ISSUE TITLE
Don’t show post button while publishing a post

### ISSUE THREAD

**Issue by paulrobertlloyd** [microdotblog/sunlit#99]
While a post is being published, two buttons are shown: ‘Cancel‘, and ‘Post‘. However, the ‘Post’ button doesn’t (and shouldn’t work), so it should not appear in this state.

<img src="https://user-images.githubusercontent.com/813383/91664829-8fdb1280-eae9-11ea-884b-85bfe1e04b0e.PNG" alt="Screenshot of Sunlit publishing a post" width="320">

**Comment by manton** [comment]
I think it should appear disabled. We'll fix that for the next update.

**Comment by manton** [comment]
Done.
